matrix:
  include:
    - language: node_js
      node_js:
        - node
        - lts/*
      cache:
        directories:
          - ~/.npm
      before_script:
        - cd frontend/reactnative/
        - npm install -g npm@latest
        - npm install
      script:
      jobs:
        include:
          - stage: deploy
            node_js: lts/*
            script:
              - npm ci
              - npx expo login -u briso -p asegroup1
              - npx expo publish --non-interactive
              - expo build:android
              # - expo build:ios
    - language: java
      before_script:
        - cd backend/
