language: java
jdk:
  - oraclejdk8
addons:
  sonarcloud:
    organization: gregam3-github
    token: 
      secure: $Sonar_token
script:
  # other script steps might be done before running the actual analysis
  - sonar-scanner
---
language: node_js
node_js:
#  - node
  - lts/*
cache:
  directories:
    - ~/.npm
before_script:
  - cd frontend/reactnative/
  - npm install -g npm@latest
  - npm install
script:
jobs:
  include:
    - stage: deploy
      node_js: lts/*
      script:
        - npm ci
        - npx expo login -u $Expo_User -p $Expo_password
        - npx expo publish --non-interactive
        - expo build:android
      #  - expo build:ios
